import type { Lang } from "./i18n";

const en = {
  nav: { home: "Home", templates: "Templates", create: "Create Biodata", formats: "Biodata Formats", guide: "Guides" },
  cta: "Create Biodata — Free",
  editor: {
    form: "Details",
    preview: "Preview",
    design: "Design",
    template: "Template",
    header: "Header",
    symbol: "Symbol",
    invocation: "Top line",
    title: "Title",
    photo: "Photo",
    uploadPhoto: "Upload photo",
    changePhoto: "Change",
    removePhoto: "Remove",
    zoom: "Zoom",
    posX: "Left – Right",
    posY: "Up – Down",
    addField: "Add field",
    addSection: "Add section",
    newField: "New field",
    newSection: "New section",
    fieldLabel: "Label",
    hideSection: "Hide section",
    showSection: "Show section",
    deleteSection: "Delete section",
    moveUp: "Move up",
    moveDown: "Move down",
    delete: "Delete",
    downloadPdf: "Download PDF",
    downloadJpg: "Download Image",
    downloadWord: "Word (.docx)",
    share: "Share on WhatsApp",
    print: "Print",
    working: "Preparing…",
    reset: "Start fresh",
    loadSample: "Fill sample data",
    resetConfirm: "Clear all details and start a new biodata?",
    saved: "Saved on this device",
    devanagariDigits: "Devanagari digits (१२३)",
    transliterate: "Type in English → Devanagari",
    accent: "Colour",
    downloadFailed: "The download didn't work. Please try again, or try JPG.",
    presetConfirm: "Switching the religion preset replaces the sections. Details with the same field are kept, but custom fields and sections you added will be removed. Continue?",
    checkPhone: "Check the mobile number: it usually has 10 digits.",
    checkEmail: "This email address looks incomplete.",
    inApp: "You're inside an in-app browser, where downloads often fail. Open this page in Chrome or Safari: tap ⋮ or ⋯ → “Open in browser”.",
    copyLink: "Copy link",
    copied: "Copied",
    kundali: "Birth chart (Kundali)",
    addKundali: "Add birth chart (kundali)",
    kundaliHint: "Fill the planets from your janma patrika, or upload a photo of it.",
    chartMode: "Fill chart",
    imageMode: "Upload kundali photo",
    lagna: "Lagna rashi (house 1)",
    house: "House",
    selectedHouse: "Tap a planet to add it to house",
    removeKundali: "Remove chart",
    uploadKundali: "Upload kundali photo",
    quickAdd: "Quick add",
    customField: "Custom field",
    uploadSymbol: "Upload god photo or logo",
    changeSymbol: "Change image",
    symbolSize: "Symbol size",
    symbolHint: "Ganesh ji, Sai Baba, Khandoba, your kuldevta or a family logo. A PNG with a transparent background looks best.",
    biodataLanguage: "Biodata language",
    religion: "Religion preset",
    premium: "Premium",
    premiumTitle: "Premium template",
    premiumBody: "Unlock every premium design once and use it for all your biodatas on this device.",
    premiumPerks: ["All premium designs (toran, jharokha, paisley, rangoli, royal)", "No “Made with” credit line", "Unlimited downloads and edits: PDF, JPG, Word"],
    premiumContinue: "Download with credit",
    unlockCta: "Unlock for ₹49",
    oneTime: "one-time",
    securePay: "Secure payment by Razorpay · UPI, cards, netbanking",
    restoreLink: "Already paid? Restore purchase",
    restorePlaceholder: "Payment ID, e.g. pay_Nx8…",
    restoreBtn: "Restore",
    restoreHint: "It's in the Razorpay receipt sent to your email or SMS.",
    opening: "Opening payment…",
    payUnavailable: "Payments aren't available right now. Please try again in a moment.",
    payFailed: "The payment didn't go through. If money was deducted, it is refunded automatically.",
    invalidId: "That doesn't look like a payment ID (it starts with pay_).",
    restoreFailed: "We couldn't find a completed ₹49 payment with that ID.",
    unlocked: "Premium unlocked",
    thanks: "Thank you! Premium designs are unlocked on this device.",
    cancel: "Cancel",
    privacy: "Your details never leave your device. No login, no watermark on free templates.",
  },
  religions: { hindu: "Hindu", jain: "Jain", buddhist: "Buddhist", muslim: "Muslim", christian: "Christian", sikh: "Sikh" },
  symbols: { none: "None", ganesh: "Ganesha", om: "Om", swastik: "Swastik", kalash: "Kalash", lotus: "Lotus", cross: "Cross", crescent: "Crescent", khanda: "Khanda", chakra: "Dhamma Chakra", jain: "Jain", custom: "My image" },
  footer: {
    tagline: "Free marriage biodata maker in English, Hindi and Marathi.",
    privacy: "Privacy",
    about: "About",
    contact: "Contact",
    terms: "Terms",
  },
  templatesPage: { all: "All", useTemplate: "Use this template", free: "Free" },
};

export type Dict = typeof en;

const hi: Dict = {
  nav: { home: "होम", templates: "टेम्पलेट", create: "बायोडाटा बनाएँ", formats: "बायोडाटा फॉर्मेट", guide: "गाइड" },
  cta: "मुफ़्त बायोडाटा बनाएँ",
  editor: {
    form: "जानकारी",
    preview: "प्रीव्यू",
    design: "डिज़ाइन",
    template: "टेम्पलेट",
    header: "शीर्षक",
    symbol: "चिह्न",
    invocation: "ऊपर की पंक्ति",
    title: "शीर्षक",
    photo: "फोटो",
    uploadPhoto: "फोटो अपलोड करें",
    changePhoto: "बदलें",
    removePhoto: "हटाएँ",
    zoom: "ज़ूम",
    posX: "बाएँ – दाएँ",
    posY: "ऊपर – नीचे",
    addField: "फ़ील्ड जोड़ें",
    addSection: "सेक्शन जोड़ें",
    newField: "नई फ़ील्ड",
    newSection: "नया सेक्शन",
    fieldLabel: "लेबल",
    hideSection: "सेक्शन छिपाएँ",
    showSection: "सेक्शन दिखाएँ",
    deleteSection: "सेक्शन हटाएँ",
    moveUp: "ऊपर",
    moveDown: "नीचे",
    delete: "हटाएँ",
    downloadPdf: "PDF डाउनलोड",
    downloadJpg: "फोटो (JPG) डाउनलोड",
    downloadWord: "Word (.docx)",
    share: "WhatsApp पर भेजें",
    print: "प्रिंट",
    working: "तैयार हो रहा है…",
    reset: "नया शुरू करें",
    loadSample: "नमूना भरें",
    resetConfirm: "सारी जानकारी मिटाकर नया बायोडाटा शुरू करें?",
    saved: "इस डिवाइस पर सेव है",
    devanagariDigits: "देवनागरी अंक (१२३)",
    transliterate: "अंग्रेज़ी में टाइप करें → हिंदी",
    accent: "रंग",
    downloadFailed: "डाउनलोड नहीं हो पाया। कृपया फिर से कोशिश करें, या JPG चुनें।",
    presetConfirm: "धर्म प्रीसेट बदलने से सेक्शन बदल जाएँगे। एक जैसी फ़ील्ड की जानकारी रहेगी, पर आपकी जोड़ी हुई फ़ील्ड और सेक्शन हट जाएँगे। आगे बढ़ें?",
    checkPhone: "मोबाइल नंबर जाँच लें: आमतौर पर इसमें 10 अंक होते हैं।",
    checkEmail: "यह ईमेल पता अधूरा लगता है।",
    inApp: "आप ऐप के अंदर वाले ब्राउज़र में हैं, जहाँ डाउनलोड अक्सर नहीं होता। यह पेज Chrome में खोलें: ⋮ या ⋯ दबाएँ → “Open in browser”।",
    copyLink: "लिंक कॉपी करें",
    copied: "कॉपी हो गया",
    kundali: "जन्म कुंडली",
    addKundali: "जन्म कुंडली जोड़ें",
    kundaliHint: "जन्मपत्री से ग्रह भरें, या कुंडली की फोटो अपलोड करें।",
    chartMode: "कुंडली भरें",
    imageMode: "कुंडली की फोटो",
    lagna: "लग्न राशि (पहला भाव)",
    house: "भाव",
    selectedHouse: "ग्रह पर टैप करें, वह इस भाव में जुड़ेगा:",
    removeKundali: "कुंडली हटाएँ",
    uploadKundali: "कुंडली की फोटो अपलोड करें",
    quickAdd: "जल्दी जोड़ें",
    customField: "अपनी फ़ील्ड",
    uploadSymbol: "भगवान की फोटो या लोगो अपलोड करें",
    changeSymbol: "फोटो बदलें",
    symbolSize: "चिह्न का आकार",
    symbolHint: "गणेश जी, साईं बाबा, कुलदेवी या परिवार का लोगो। पारदर्शी बैकग्राउंड वाली PNG सबसे अच्छी लगती है।",
    biodataLanguage: "बायोडाटा की भाषा",
    religion: "धर्म प्रीसेट",
    premium: "प्रीमियम",
    premiumTitle: "प्रीमियम टेम्पलेट",
    premiumBody: "एक बार अनलॉक करें और इस डिवाइस पर अपने सभी बायोडाटा के लिए हर प्रीमियम डिज़ाइन इस्तेमाल करें।",
    premiumPerks: ["सभी प्रीमियम डिज़ाइन (तोरण, झरोखा, पैस्ले, रंगोली, रॉयल)", "नीचे कोई “Made with” क्रेडिट नहीं", "असीमित डाउनलोड और बदलाव: PDF, JPG, Word"],
    premiumContinue: "क्रेडिट के साथ डाउनलोड",
    unlockCta: "₹49 में अनलॉक करें",
    oneTime: "एक बार",
    securePay: "Razorpay द्वारा सुरक्षित भुगतान · UPI, कार्ड, नेटबैंकिंग",
    restoreLink: "पहले भुगतान कर चुके हैं? खरीद वापस पाएँ",
    restorePlaceholder: "पेमेंट ID, जैसे pay_Nx8…",
    restoreBtn: "वापस पाएँ",
    restoreHint: "यह Razorpay की रसीद (ईमेल या SMS) में मिलेगा।",
    opening: "भुगतान खुल रहा है…",
    payUnavailable: "अभी भुगतान उपलब्ध नहीं है। कृपया थोड़ी देर बाद फिर कोशिश करें।",
    payFailed: "भुगतान पूरा नहीं हुआ। अगर पैसे कटे हैं तो वे अपने-आप वापस आ जाएँगे।",
    invalidId: "यह पेमेंट ID सही नहीं लगती (यह pay_ से शुरू होती है)।",
    restoreFailed: "इस ID से ₹49 का पूरा हुआ भुगतान नहीं मिला।",
    unlocked: "प्रीमियम अनलॉक है",
    thanks: "धन्यवाद! इस डिवाइस पर प्रीमियम डिज़ाइन अनलॉक हो गए हैं।",
    cancel: "रद्द करें",
    privacy: "आपकी जानकारी आपके डिवाइस से बाहर नहीं जाती। कोई लॉगिन नहीं, मुफ़्त टेम्पलेट पर कोई वॉटरमार्क नहीं।",
  },
  religions: { hindu: "हिंदू", jain: "जैन", buddhist: "बौद्ध", muslim: "मुस्लिम", christian: "ईसाई", sikh: "सिख" },
  symbols: { none: "कोई नहीं", ganesh: "गणेश", om: "ॐ", swastik: "स्वस्तिक", kalash: "कलश", lotus: "कमल", cross: "क्रॉस", crescent: "चाँद-तारा", khanda: "खंडा", chakra: "धम्म चक्र", jain: "जैन", custom: "मेरी फोटो" },
  footer: {
    tagline: "हिंदी, मराठी और अंग्रेज़ी में मुफ़्त शादी का बायोडाटा मेकर।",
    privacy: "प्राइवेसी",
    about: "हमारे बारे में",
    contact: "संपर्क",
    terms: "नियम",
  },
  templatesPage: { all: "सभी", useTemplate: "यह टेम्पलेट चुनें", free: "मुफ़्त" },
};

const mr: Dict = {
  nav: { home: "होम", templates: "टेम्पलेट्स", create: "बायोडाटा बनवा", formats: "बायोडाटा फॉरमॅट", guide: "मार्गदर्शन" },
  cta: "मोफत बायोडाटा बनवा",
  editor: {
    form: "माहिती",
    preview: "पूर्वावलोकन",
    design: "डिझाईन",
    template: "टेम्पलेट",
    header: "शीर्षक",
    symbol: "चिन्ह",
    invocation: "वरची ओळ",
    title: "शीर्षक",
    photo: "फोटो",
    uploadPhoto: "फोटो अपलोड करा",
    changePhoto: "बदला",
    removePhoto: "काढा",
    zoom: "झूम",
    posX: "डावीकडे – उजवीकडे",
    posY: "वर – खाली",
    addField: "माहिती जोडा",
    addSection: "विभाग जोडा",
    newField: "नवीन माहिती",
    newSection: "नवीन विभाग",
    fieldLabel: "लेबल",
    hideSection: "विभाग लपवा",
    showSection: "विभाग दाखवा",
    deleteSection: "विभाग काढा",
    moveUp: "वर",
    moveDown: "खाली",
    delete: "काढा",
    downloadPdf: "PDF डाउनलोड",
    downloadJpg: "फोटो (JPG) डाउनलोड",
    downloadWord: "Word (.docx)",
    share: "WhatsApp वर पाठवा",
    print: "प्रिंट",
    working: "तयार होत आहे…",
    reset: "नवीन सुरू करा",
    loadSample: "नमुना माहिती भरा",
    resetConfirm: "सर्व माहिती पुसून नवीन बायोडाटा सुरू करायचा?",
    saved: "या डिव्हाइसवर सेव्ह आहे",
    devanagariDigits: "मराठी अंक (१२३)",
    transliterate: "इंग्रजीत टाइप करा → मराठी",
    accent: "रंग",
    downloadFailed: "डाउनलोड झाले नाही. कृपया पुन्हा प्रयत्न करा, किंवा JPG निवडा.",
    presetConfirm: "धर्म प्रीसेट बदलल्यावर विभाग बदलतील. सारख्या ओळींची माहिती राहील, पण तुम्ही जोडलेल्या ओळी व विभाग काढले जातील. पुढे जायचे?",
    checkPhone: "मोबाईल नंबर तपासा: साधारणपणे 10 अंक असतात.",
    checkEmail: "हा ईमेल पत्ता अपूर्ण वाटतो.",
    inApp: "तुम्ही ॲपमधील ब्राउझरमध्ये आहात, येथे डाउनलोड अनेकदा होत नाही. हे पान Chrome मध्ये उघडा: ⋮ किंवा ⋯ दाबा → “Open in browser”.",
    copyLink: "लिंक कॉपी करा",
    copied: "कॉपी झाली",
    kundali: "जन्म कुंडली",
    addKundali: "जन्म कुंडली जोडा",
    kundaliHint: "जन्मपत्रिकेतील ग्रह भरा, किंवा पत्रिकेचा फोटो अपलोड करा.",
    chartMode: "कुंडली भरा",
    imageMode: "पत्रिकेचा फोटो",
    lagna: "लग्न रास (पहिले स्थान)",
    house: "स्थान",
    selectedHouse: "ग्रहावर टॅप करा, तो या स्थानात जोडला जाईल:",
    removeKundali: "कुंडली काढा",
    uploadKundali: "पत्रिकेचा फोटो अपलोड करा",
    quickAdd: "पटकन जोडा",
    customField: "स्वतःची माहिती",
    uploadSymbol: "देवाचा फोटो किंवा लोगो अपलोड करा",
    changeSymbol: "फोटो बदला",
    symbolSize: "चिन्हाचा आकार",
    symbolHint: "गणपती बाप्पा, स्वामी समर्थ, खंडोबा, कुलदैवत किंवा कुटुंबाचा लोगो. पारदर्शक बॅकग्राउंडची PNG सर्वात छान दिसते.",
    biodataLanguage: "बायोडाटाची भाषा",
    religion: "धर्म प्रीसेट",
    premium: "प्रीमियम",
    premiumTitle: "प्रीमियम टेम्पलेट",
    premiumBody: "एकदाच अनलॉक करा आणि या डिव्हाइसवर तुमच्या सर्व बायोडाटासाठी प्रत्येक प्रीमियम डिझाईन वापरा.",
    premiumPerks: ["सर्व प्रीमियम डिझाईन्स (तोरण, झरोखा, पैसले, रांगोळी, रॉयल)", "तळाशी “Made with” क्रेडिट नाही", "अमर्यादित डाउनलोड आणि बदल: PDF, JPG, Word"],
    premiumContinue: "क्रेडिटसह डाउनलोड",
    unlockCta: "₹49 मध्ये अनलॉक करा",
    oneTime: "एकदाच",
    securePay: "Razorpay द्वारे सुरक्षित पेमेंट · UPI, कार्ड, नेटबँकिंग",
    restoreLink: "आधीच पेमेंट केले आहे? खरेदी परत मिळवा",
    restorePlaceholder: "पेमेंट ID, उदा. pay_Nx8…",
    restoreBtn: "परत मिळवा",
    restoreHint: "हा Razorpay च्या पावतीत (ईमेल किंवा SMS) मिळेल.",
    opening: "पेमेंट उघडत आहे…",
    payUnavailable: "सध्या पेमेंट उपलब्ध नाही. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.",
    payFailed: "पेमेंट पूर्ण झाले नाही. पैसे कापले गेले असतील तर ते आपोआप परत येतील.",
    invalidId: "हा पेमेंट ID योग्य वाटत नाही (तो pay_ ने सुरू होतो).",
    restoreFailed: "या ID ने ₹49 चे पूर्ण झालेले पेमेंट सापडले नाही.",
    unlocked: "प्रीमियम अनलॉक आहे",
    thanks: "धन्यवाद! या डिव्हाइसवर प्रीमियम डिझाईन्स अनलॉक झाले आहेत.",
    cancel: "रद्द करा",
    privacy: "तुमची माहिती तुमच्या डिव्हाइसबाहेर जात नाही. लॉगिन नाही, मोफत टेम्पलेटवर वॉटरमार्क नाही.",
  },
  religions: { hindu: "हिंदू", jain: "जैन", buddhist: "बौद्ध", muslim: "मुस्लिम", christian: "ख्रिश्चन", sikh: "शीख" },
  symbols: { none: "काही नाही", ganesh: "गणपती", om: "ॐ", swastik: "स्वस्तिक", kalash: "कलश", lotus: "कमळ", cross: "क्रॉस", crescent: "चंद्र-तारा", khanda: "खंडा", chakra: "धम्मचक्र", jain: "जैन", custom: "माझा फोटो" },
  footer: {
    tagline: "मराठी, हिंदी आणि इंग्रजीत मोफत लग्नाचा बायोडाटा मेकर.",
    privacy: "गोपनीयता",
    about: "आमच्याबद्दल",
    contact: "संपर्क",
    terms: "अटी",
  },
  templatesPage: { all: "सर्व", useTemplate: "हे टेम्पलेट वापरा", free: "मोफत" },
};

export const DICTS: Record<Lang, Dict> = { en, hi, mr };
